<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Refit-Keycloak.Application\Refit-Keycloak.Application.csproj" />
    <ProjectReference Include="..\Refit-Keycloak.Infrastructure\Refit-Keycloak.Infrastructure.csproj" />
    <ProjectReference Include="..\Refit-Keycloak.Domain\Refit-Keycloak.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
